### ISSUE TITLE
No such file or directory: 'config.txt'

### ISSUE THREAD

**Issue by shujaatak** [KorayKaya/Realtime-Stock-Crypto-Price#1]
There is no config.txt file in the repository and also there is no documentation about its structure to reproduce by ourselves. Otherwise the project looks promising!

```
txt = open("config.txt")
FileNotFoundError: [Errno 2] No such file or directory: 'config.txt'
```

**Comment by shujaatak** [comment]
Oh the config.txt is there in the repository but the program can't find it.

**Comment by kkayam** [comment]
Interesting, are you using windows or linux?

**Comment by shujaatak** [comment]
I had somehow misplaced config.txt, but now as the program can read it but it throws index error. 
Can you please verify that the project in the current state work on your system? Also fontsize errors etc.
